apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qrv494ie3-go 
  janus-idp.io/tekton: qrv494ie3-go
  backstage.io/kubernetes-id: qrv494ie3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qrv494ie3-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  